export const typesLogin = {
    LOGIN: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    REGISTER: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
}

export const typesUser = {
    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    DELETE_USER: 'DELETE_USER',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    UPDATE_PHOTO: 'UPDATE_PHOTO',
    UPDATE_PHOTO_SUCCESS: 'UPDATE_PHOTO_SUCCESS',
    UPDATE_PHOTO_FAILURE: 'UPDATE_PHOTO_FAILURE',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_EMAIL_SUCCESS: 'UPDATE_EMAIL_SUCCESS',
    UPDATE_EMAIL_FAILURE: 'UPDATE_EMAIL_FAILURE',

    SET_UP_RECAPTCHA: 'SET_UP_RECAPTCHA',
    SET_UP_RECAPTCHA_SUCCESS: 'SET_UP_RECAPTCHA_SUCCESS',
    SET_UP_RECAPTCHA_FAILURE: 'SET_UP_RECAPTCHA_FAILURE',

    VERIFY_RECAPTCHA: 'VERIFY_RECAPTCHA',
    VERIFY_RECAPTCHA_SUCCESS: 'VERIFY_RECAPTCHA_SUCCESS',
    VERIFY_RECAPTCHA_FAILURE: 'VERIFY_RECAPTCHA_FAILURE',
    
    SIGN_IN_WITH_PHONE: 'SIGN_IN_WITH_PHONE',
    SIGN_IN_WITH_PHONE_SUCCESS: 'SIGN_IN_WITH_PHONE_SUCCESS',
    SIGN_IN_WITH_PHONE_FAILURE: 'SIGN_IN_WITH_PHONE_FAILURE',
    
}